/* tslint:disable */
/* eslint-disable */
/**
 * Beacon API
 * Real-time vehicle tracking API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

export interface BaseResponseBodyGpsHistoryResponseBody {
    'data': GpsHistoryResponse;
    'message': string;
    'status': boolean;
}
export interface BaseResponseBodyGpsPointResponseBody {
    'data': GpsPointResponse;
    'message': string;
    'status': boolean;
}
export interface BaseResponseBodyGpsResponseBody {
    'data': GpsResponse;
    'message': string;
    'status': boolean;
}
export interface BaseResponseBodyHealthCheckResponseBody {
    'data': object;
    'message': string;
    'status': boolean;
}
export interface BaseResponseBodyListGpsPointResponseBody {
    'data': Array<GpsPointResponse> | null;
    'message': string;
    'status': boolean;
}
export interface BaseResponseBodyListGpsResponseBody {
    'data': Array<GpsResponse> | null;
    'message': string;
    'status': boolean;
}
export interface BaseResponseBodyListVehicleResponseBody {
    'data': Array<VehicleResponse> | null;
    'message': string;
    'status': boolean;
}
export interface BaseResponseBodyVehicleResponseBody {
    'data': VehicleResponse;
    'message': string;
    'status': boolean;
}
export interface Coordinate {
    'latitude': number;
    'longitude': number;
    'updated_at': string;
}
export interface CreateGpsPoint {
    'bearing': number;
    'gps_id': number;
    'latitude': number;
    'longitude': number;
    'timestamp': number;
}
export interface CreateGpsRequestBody {
    'sn': string;
    'vehicle_id': number;
}
export interface CreateVehicleRequestBody {
    'plate_number': string;
    'vehicle_type': CreateVehicleRequestBodyVehicleTypeEnum;
}

export const CreateVehicleRequestBodyVehicleTypeEnum = {
    Car: 'car',
    Bus: 'bus',
    Truck: 'truck',
    Van: 'van',
} as const;

export type CreateVehicleRequestBodyVehicleTypeEnum = typeof CreateVehicleRequestBodyVehicleTypeEnum[keyof typeof CreateVehicleRequestBodyVehicleTypeEnum];

export interface GpsHistoryResponse {
    'coordinates': Array<Coordinate> | null;
    'gps_id': number;
    'gps_sn': string;
}
export interface GpsPointResponse {
    'bearing': number;
    'created_at': string;
    'gps_id': number;
    'id': number;
    'latitude': number;
    'longitude': number;
    'timestamp': number;
}
export interface GpsResponse {
    'created_at': string;
    'id': number;
    'last_coordinate': Coordinate;
    'sn': string;
    'vehicle': VehicleResponse;
}
export interface MyError {
    'data': any;
    'message': string;
    'status': number;
}
export interface VehicleResponse {
    'created_at': string;
    'id': number;
    'plate_number': string;
    'vehicle_type': VehicleResponseVehicleTypeEnum;
}

export const VehicleResponseVehicleTypeEnum = {
    Car: 'car',
    Bus: 'bus',
    Truck: 'truck',
    Van: 'van',
} as const;

export type VehicleResponseVehicleTypeEnum = typeof VehicleResponseVehicleTypeEnum[keyof typeof VehicleResponseVehicleTypeEnum];


/**
 * GPSDevicesApi - axios parameter creator
 */
export const GPSDevicesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Register a GPS device
         * @param {CreateGpsRequestBody} [createGpsRequestBody] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createGpsDevice: async (createGpsRequestBody?: CreateGpsRequestBody, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/gps-devices`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createGpsRequestBody, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Delete a GPS device
         * @param {number} id Unique identifier for the GPS device
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteGpsDevice: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('deleteGpsDevice', 'id', id)
            const localVarPath = `/api/v1/gps-devices/{id}`
                .replace('{id}', encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get a GPS device
         * @param {number} id Unique identifier for the GPS device
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getGpsDevice: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getGpsDevice', 'id', id)
            const localVarPath = `/api/v1/gps-devices/{id}`
                .replace('{id}', encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary List GPS devices
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getGpsDevices: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/gps-devices`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get GPS device location history
         * @param {number} id Unique identifier for the GPS device
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getGpsHistory: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getGpsHistory', 'id', id)
            const localVarPath = `/api/v1/gps-devices/{id}/history`
                .replace('{id}', encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * GPSDevicesApi - functional programming interface
 */
export const GPSDevicesApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = GPSDevicesApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Register a GPS device
         * @param {CreateGpsRequestBody} [createGpsRequestBody] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createGpsDevice(createGpsRequestBody?: CreateGpsRequestBody, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseBodyGpsResponseBody>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createGpsDevice(createGpsRequestBody, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['GPSDevicesApi.createGpsDevice']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Delete a GPS device
         * @param {number} id Unique identifier for the GPS device
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteGpsDevice(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteGpsDevice(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['GPSDevicesApi.deleteGpsDevice']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get a GPS device
         * @param {number} id Unique identifier for the GPS device
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getGpsDevice(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseBodyGpsResponseBody>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getGpsDevice(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['GPSDevicesApi.getGpsDevice']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary List GPS devices
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getGpsDevices(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseBodyListGpsResponseBody>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getGpsDevices(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['GPSDevicesApi.getGpsDevices']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get GPS device location history
         * @param {number} id Unique identifier for the GPS device
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getGpsHistory(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseBodyGpsHistoryResponseBody>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getGpsHistory(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['GPSDevicesApi.getGpsHistory']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * GPSDevicesApi - factory interface
 */
export const GPSDevicesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = GPSDevicesApiFp(configuration)
    return {
        /**
         * 
         * @summary Register a GPS device
         * @param {CreateGpsRequestBody} [createGpsRequestBody] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createGpsDevice(createGpsRequestBody?: CreateGpsRequestBody, options?: RawAxiosRequestConfig): AxiosPromise<BaseResponseBodyGpsResponseBody> {
            return localVarFp.createGpsDevice(createGpsRequestBody, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Delete a GPS device
         * @param {number} id Unique identifier for the GPS device
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteGpsDevice(id: number, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.deleteGpsDevice(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get a GPS device
         * @param {number} id Unique identifier for the GPS device
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getGpsDevice(id: number, options?: RawAxiosRequestConfig): AxiosPromise<BaseResponseBodyGpsResponseBody> {
            return localVarFp.getGpsDevice(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary List GPS devices
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getGpsDevices(options?: RawAxiosRequestConfig): AxiosPromise<BaseResponseBodyListGpsResponseBody> {
            return localVarFp.getGpsDevices(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get GPS device location history
         * @param {number} id Unique identifier for the GPS device
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getGpsHistory(id: number, options?: RawAxiosRequestConfig): AxiosPromise<BaseResponseBodyGpsHistoryResponseBody> {
            return localVarFp.getGpsHistory(id, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * GPSDevicesApi - object-oriented interface
 */
export class GPSDevicesApi extends BaseAPI {
    /**
     * 
     * @summary Register a GPS device
     * @param {CreateGpsRequestBody} [createGpsRequestBody] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public createGpsDevice(createGpsRequestBody?: CreateGpsRequestBody, options?: RawAxiosRequestConfig) {
        return GPSDevicesApiFp(this.configuration).createGpsDevice(createGpsRequestBody, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Delete a GPS device
     * @param {number} id Unique identifier for the GPS device
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public deleteGpsDevice(id: number, options?: RawAxiosRequestConfig) {
        return GPSDevicesApiFp(this.configuration).deleteGpsDevice(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get a GPS device
     * @param {number} id Unique identifier for the GPS device
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getGpsDevice(id: number, options?: RawAxiosRequestConfig) {
        return GPSDevicesApiFp(this.configuration).getGpsDevice(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary List GPS devices
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getGpsDevices(options?: RawAxiosRequestConfig) {
        return GPSDevicesApiFp(this.configuration).getGpsDevices(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get GPS device location history
     * @param {number} id Unique identifier for the GPS device
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getGpsHistory(id: number, options?: RawAxiosRequestConfig) {
        return GPSDevicesApiFp(this.configuration).getGpsHistory(id, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * GPSPointsApi - axios parameter creator
 */
export const GPSPointsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Record a GPS point
         * @param {CreateGpsPoint} [createGpsPoint] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createGpsPoint: async (createGpsPoint?: CreateGpsPoint, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/gps-points`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createGpsPoint, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary List GPS points
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getGpsPoints: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/gps-points`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * GPSPointsApi - functional programming interface
 */
export const GPSPointsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = GPSPointsApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Record a GPS point
         * @param {CreateGpsPoint} [createGpsPoint] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createGpsPoint(createGpsPoint?: CreateGpsPoint, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseBodyGpsPointResponseBody>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createGpsPoint(createGpsPoint, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['GPSPointsApi.createGpsPoint']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary List GPS points
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getGpsPoints(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseBodyListGpsPointResponseBody>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getGpsPoints(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['GPSPointsApi.getGpsPoints']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * GPSPointsApi - factory interface
 */
export const GPSPointsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = GPSPointsApiFp(configuration)
    return {
        /**
         * 
         * @summary Record a GPS point
         * @param {CreateGpsPoint} [createGpsPoint] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createGpsPoint(createGpsPoint?: CreateGpsPoint, options?: RawAxiosRequestConfig): AxiosPromise<BaseResponseBodyGpsPointResponseBody> {
            return localVarFp.createGpsPoint(createGpsPoint, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary List GPS points
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getGpsPoints(options?: RawAxiosRequestConfig): AxiosPromise<BaseResponseBodyListGpsPointResponseBody> {
            return localVarFp.getGpsPoints(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * GPSPointsApi - object-oriented interface
 */
export class GPSPointsApi extends BaseAPI {
    /**
     * 
     * @summary Record a GPS point
     * @param {CreateGpsPoint} [createGpsPoint] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public createGpsPoint(createGpsPoint?: CreateGpsPoint, options?: RawAxiosRequestConfig) {
        return GPSPointsApiFp(this.configuration).createGpsPoint(createGpsPoint, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary List GPS points
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getGpsPoints(options?: RawAxiosRequestConfig) {
        return GPSPointsApiFp(this.configuration).getGpsPoints(options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * HealthApi - axios parameter creator
 */
export const HealthApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Health check
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        healthCheck: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/health`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * HealthApi - functional programming interface
 */
export const HealthApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = HealthApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Health check
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async healthCheck(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseBodyHealthCheckResponseBody>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.healthCheck(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['HealthApi.healthCheck']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * HealthApi - factory interface
 */
export const HealthApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = HealthApiFp(configuration)
    return {
        /**
         * 
         * @summary Health check
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        healthCheck(options?: RawAxiosRequestConfig): AxiosPromise<BaseResponseBodyHealthCheckResponseBody> {
            return localVarFp.healthCheck(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * HealthApi - object-oriented interface
 */
export class HealthApi extends BaseAPI {
    /**
     * 
     * @summary Health check
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public healthCheck(options?: RawAxiosRequestConfig) {
        return HealthApiFp(this.configuration).healthCheck(options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * VehiclesApi - axios parameter creator
 */
export const VehiclesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Create new vehicles
         * @param {CreateVehicleRequestBody} [createVehicleRequestBody] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createVehicle: async (createVehicleRequestBody?: CreateVehicleRequestBody, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/vehicles`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createVehicleRequestBody, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Delete vehicle
         * @param {number} id Unique identifier for the vehicle
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteVehicle: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('deleteVehicle', 'id', id)
            const localVarPath = `/api/v1/vehicles/{id}`
                .replace('{id}', encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get vehicle
         * @param {number} id Unique identifier for the vehicle
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSingleVehicle: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getSingleVehicle', 'id', id)
            const localVarPath = `/api/v1/vehicles/{id}`
                .replace('{id}', encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary List out vehicles
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getVehicles: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/vehicles`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * VehiclesApi - functional programming interface
 */
export const VehiclesApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = VehiclesApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Create new vehicles
         * @param {CreateVehicleRequestBody} [createVehicleRequestBody] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createVehicle(createVehicleRequestBody?: CreateVehicleRequestBody, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseBodyVehicleResponseBody>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createVehicle(createVehicleRequestBody, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['VehiclesApi.createVehicle']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Delete vehicle
         * @param {number} id Unique identifier for the vehicle
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteVehicle(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteVehicle(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['VehiclesApi.deleteVehicle']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get vehicle
         * @param {number} id Unique identifier for the vehicle
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getSingleVehicle(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseBodyVehicleResponseBody>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getSingleVehicle(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['VehiclesApi.getSingleVehicle']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary List out vehicles
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getVehicles(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseBodyListVehicleResponseBody>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getVehicles(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['VehiclesApi.getVehicles']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * VehiclesApi - factory interface
 */
export const VehiclesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = VehiclesApiFp(configuration)
    return {
        /**
         * 
         * @summary Create new vehicles
         * @param {CreateVehicleRequestBody} [createVehicleRequestBody] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createVehicle(createVehicleRequestBody?: CreateVehicleRequestBody, options?: RawAxiosRequestConfig): AxiosPromise<BaseResponseBodyVehicleResponseBody> {
            return localVarFp.createVehicle(createVehicleRequestBody, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Delete vehicle
         * @param {number} id Unique identifier for the vehicle
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteVehicle(id: number, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.deleteVehicle(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get vehicle
         * @param {number} id Unique identifier for the vehicle
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSingleVehicle(id: number, options?: RawAxiosRequestConfig): AxiosPromise<BaseResponseBodyVehicleResponseBody> {
            return localVarFp.getSingleVehicle(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary List out vehicles
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getVehicles(options?: RawAxiosRequestConfig): AxiosPromise<BaseResponseBodyListVehicleResponseBody> {
            return localVarFp.getVehicles(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * VehiclesApi - object-oriented interface
 */
export class VehiclesApi extends BaseAPI {
    /**
     * 
     * @summary Create new vehicles
     * @param {CreateVehicleRequestBody} [createVehicleRequestBody] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public createVehicle(createVehicleRequestBody?: CreateVehicleRequestBody, options?: RawAxiosRequestConfig) {
        return VehiclesApiFp(this.configuration).createVehicle(createVehicleRequestBody, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Delete vehicle
     * @param {number} id Unique identifier for the vehicle
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public deleteVehicle(id: number, options?: RawAxiosRequestConfig) {
        return VehiclesApiFp(this.configuration).deleteVehicle(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get vehicle
     * @param {number} id Unique identifier for the vehicle
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getSingleVehicle(id: number, options?: RawAxiosRequestConfig) {
        return VehiclesApiFp(this.configuration).getSingleVehicle(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary List out vehicles
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getVehicles(options?: RawAxiosRequestConfig) {
        return VehiclesApiFp(this.configuration).getVehicles(options).then((request) => request(this.axios, this.basePath));
    }
}



