/* tslint:disable */
/* eslint-disable */
/**
 * Beacon API
 * Real-time vehicle tracking API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

export interface GpsCoordinate {
    'latitude': number;
    'longitude': number;
    'updated_at': string;
}
export interface GpsCreateGpsRequest {
    'sn': string;
    'vehicle_id': number;
}
export interface GpsGpsHistoryResponse {
    'coordinates': Array<GpsCoordinate>;
    'gps_id': number;
    'gps_sn': string;
}
export interface GpsGpsResponse {
    'created_at': string;
    'id': number;
    'last_coordinate': GpsCoordinate;
    'sn': string;
    'vehicle': VehiclesVehicleResponse;
}
export interface GpspointsCreateGpsPoint {
    'bearing': number;
    'gps_id': number;
    'latitude': number;
    'longitude': number;
    'timestamp': number;
}
export interface GpspointsGpsPointResponse {
    'bearing': number;
    'created_at': string;
    'gps_id': number;
    'id': number;
    'latitude': number;
    'longitude': number;
    'timestamp': number;
}
export interface VehiclesCreateVehicleRequest {
    'plate_number': string;
    'vehicle_type': VehiclesVehicleType;
}


export interface VehiclesVehicleResponse {
    'created_at': string;
    'id': number;
    'plate_number': string;
    'vehicle_type': VehiclesVehicleType;
}



export const VehiclesVehicleType = {
    Car: 'car',
    Bus: 'bus',
    Truck: 'truck',
    Van: 'van',
} as const;

export type VehiclesVehicleType = typeof VehiclesVehicleType[keyof typeof VehiclesVehicleType];



/**
 * GpsApi - axios parameter creator
 */
export const GpsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary List GPS devices
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        gpsDevicesGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/gps-devices`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Delete a GPS device
         * @param {number} id GPS ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        gpsDevicesIdDelete: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('gpsDevicesIdDelete', 'id', id)
            const localVarPath = `/gps-devices/{id}`
                .replace('{id}', encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get a GPS device
         * @param {number} id GPS ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        gpsDevicesIdGet: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('gpsDevicesIdGet', 'id', id)
            const localVarPath = `/gps-devices/{id}`
                .replace('{id}', encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get a GpsHistory ...
         * @param {number} id GPS ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        gpsDevicesIdHistoryGet: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('gpsDevicesIdHistoryGet', 'id', id)
            const localVarPath = `/gps-devices/{id}/history`
                .replace('{id}', encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Register a GPS device
         * @param {GpsCreateGpsRequest} body GPS payload
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        gpsDevicesPost: async (body: GpsCreateGpsRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            assertParamExists('gpsDevicesPost', 'body', body)
            const localVarPath = `/gps-devices`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(body, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * GpsApi - functional programming interface
 */
export const GpsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = GpsApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary List GPS devices
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async gpsDevicesGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<GpsGpsResponse>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.gpsDevicesGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['GpsApi.gpsDevicesGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Delete a GPS device
         * @param {number} id GPS ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async gpsDevicesIdDelete(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.gpsDevicesIdDelete(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['GpsApi.gpsDevicesIdDelete']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get a GPS device
         * @param {number} id GPS ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async gpsDevicesIdGet(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GpsGpsResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.gpsDevicesIdGet(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['GpsApi.gpsDevicesIdGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get a GpsHistory ...
         * @param {number} id GPS ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async gpsDevicesIdHistoryGet(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GpsGpsHistoryResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.gpsDevicesIdHistoryGet(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['GpsApi.gpsDevicesIdHistoryGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Register a GPS device
         * @param {GpsCreateGpsRequest} body GPS payload
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async gpsDevicesPost(body: GpsCreateGpsRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GpsGpsResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.gpsDevicesPost(body, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['GpsApi.gpsDevicesPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * GpsApi - factory interface
 */
export const GpsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = GpsApiFp(configuration)
    return {
        /**
         * 
         * @summary List GPS devices
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        gpsDevicesGet(options?: RawAxiosRequestConfig): AxiosPromise<Array<GpsGpsResponse>> {
            return localVarFp.gpsDevicesGet(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Delete a GPS device
         * @param {number} id GPS ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        gpsDevicesIdDelete(id: number, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.gpsDevicesIdDelete(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get a GPS device
         * @param {number} id GPS ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        gpsDevicesIdGet(id: number, options?: RawAxiosRequestConfig): AxiosPromise<GpsGpsResponse> {
            return localVarFp.gpsDevicesIdGet(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get a GpsHistory ...
         * @param {number} id GPS ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        gpsDevicesIdHistoryGet(id: number, options?: RawAxiosRequestConfig): AxiosPromise<GpsGpsHistoryResponse> {
            return localVarFp.gpsDevicesIdHistoryGet(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Register a GPS device
         * @param {GpsCreateGpsRequest} body GPS payload
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        gpsDevicesPost(body: GpsCreateGpsRequest, options?: RawAxiosRequestConfig): AxiosPromise<GpsGpsResponse> {
            return localVarFp.gpsDevicesPost(body, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * GpsApi - object-oriented interface
 */
export class GpsApi extends BaseAPI {
    /**
     * 
     * @summary List GPS devices
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public gpsDevicesGet(options?: RawAxiosRequestConfig) {
        return GpsApiFp(this.configuration).gpsDevicesGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Delete a GPS device
     * @param {number} id GPS ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public gpsDevicesIdDelete(id: number, options?: RawAxiosRequestConfig) {
        return GpsApiFp(this.configuration).gpsDevicesIdDelete(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get a GPS device
     * @param {number} id GPS ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public gpsDevicesIdGet(id: number, options?: RawAxiosRequestConfig) {
        return GpsApiFp(this.configuration).gpsDevicesIdGet(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get a GpsHistory ...
     * @param {number} id GPS ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public gpsDevicesIdHistoryGet(id: number, options?: RawAxiosRequestConfig) {
        return GpsApiFp(this.configuration).gpsDevicesIdHistoryGet(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Register a GPS device
     * @param {GpsCreateGpsRequest} body GPS payload
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public gpsDevicesPost(body: GpsCreateGpsRequest, options?: RawAxiosRequestConfig) {
        return GpsApiFp(this.configuration).gpsDevicesPost(body, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * GpsPointsApi - axios parameter creator
 */
export const GpsPointsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary List GPS points
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        gpsPointsGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/gps-points`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Record a GPS point
         * @param {GpspointsCreateGpsPoint} body GPS point payload
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        gpsPointsPost: async (body: GpspointsCreateGpsPoint, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            assertParamExists('gpsPointsPost', 'body', body)
            const localVarPath = `/gps-points`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(body, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * GpsPointsApi - functional programming interface
 */
export const GpsPointsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = GpsPointsApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary List GPS points
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async gpsPointsGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<GpspointsGpsPointResponse>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.gpsPointsGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['GpsPointsApi.gpsPointsGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Record a GPS point
         * @param {GpspointsCreateGpsPoint} body GPS point payload
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async gpsPointsPost(body: GpspointsCreateGpsPoint, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GpspointsGpsPointResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.gpsPointsPost(body, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['GpsPointsApi.gpsPointsPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * GpsPointsApi - factory interface
 */
export const GpsPointsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = GpsPointsApiFp(configuration)
    return {
        /**
         * 
         * @summary List GPS points
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        gpsPointsGet(options?: RawAxiosRequestConfig): AxiosPromise<Array<GpspointsGpsPointResponse>> {
            return localVarFp.gpsPointsGet(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Record a GPS point
         * @param {GpspointsCreateGpsPoint} body GPS point payload
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        gpsPointsPost(body: GpspointsCreateGpsPoint, options?: RawAxiosRequestConfig): AxiosPromise<GpspointsGpsPointResponse> {
            return localVarFp.gpsPointsPost(body, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * GpsPointsApi - object-oriented interface
 */
export class GpsPointsApi extends BaseAPI {
    /**
     * 
     * @summary List GPS points
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public gpsPointsGet(options?: RawAxiosRequestConfig) {
        return GpsPointsApiFp(this.configuration).gpsPointsGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Record a GPS point
     * @param {GpspointsCreateGpsPoint} body GPS point payload
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public gpsPointsPost(body: GpspointsCreateGpsPoint, options?: RawAxiosRequestConfig) {
        return GpsPointsApiFp(this.configuration).gpsPointsPost(body, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * VehiclesApi - axios parameter creator
 */
export const VehiclesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary List vehicles
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        vehiclesGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/vehicles`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Delete a vehicle
         * @param {number} id Vehicle ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        vehiclesIdDelete: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('vehiclesIdDelete', 'id', id)
            const localVarPath = `/vehicles/{id}`
                .replace('{id}', encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get a vehicle
         * @param {number} id Vehicle ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        vehiclesIdGet: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('vehiclesIdGet', 'id', id)
            const localVarPath = `/vehicles/{id}`
                .replace('{id}', encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary CreateVehicle ...
         * @param {VehiclesCreateVehicleRequest} body Vehicle payload
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        vehiclesPost: async (body: VehiclesCreateVehicleRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            assertParamExists('vehiclesPost', 'body', body)
            const localVarPath = `/vehicles`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(body, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * VehiclesApi - functional programming interface
 */
export const VehiclesApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = VehiclesApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary List vehicles
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async vehiclesGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<VehiclesVehicleResponse>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.vehiclesGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['VehiclesApi.vehiclesGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Delete a vehicle
         * @param {number} id Vehicle ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async vehiclesIdDelete(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.vehiclesIdDelete(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['VehiclesApi.vehiclesIdDelete']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get a vehicle
         * @param {number} id Vehicle ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async vehiclesIdGet(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<VehiclesVehicleResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.vehiclesIdGet(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['VehiclesApi.vehiclesIdGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary CreateVehicle ...
         * @param {VehiclesCreateVehicleRequest} body Vehicle payload
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async vehiclesPost(body: VehiclesCreateVehicleRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<VehiclesVehicleResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.vehiclesPost(body, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['VehiclesApi.vehiclesPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * VehiclesApi - factory interface
 */
export const VehiclesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = VehiclesApiFp(configuration)
    return {
        /**
         * 
         * @summary List vehicles
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        vehiclesGet(options?: RawAxiosRequestConfig): AxiosPromise<Array<VehiclesVehicleResponse>> {
            return localVarFp.vehiclesGet(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Delete a vehicle
         * @param {number} id Vehicle ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        vehiclesIdDelete(id: number, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.vehiclesIdDelete(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get a vehicle
         * @param {number} id Vehicle ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        vehiclesIdGet(id: number, options?: RawAxiosRequestConfig): AxiosPromise<VehiclesVehicleResponse> {
            return localVarFp.vehiclesIdGet(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary CreateVehicle ...
         * @param {VehiclesCreateVehicleRequest} body Vehicle payload
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        vehiclesPost(body: VehiclesCreateVehicleRequest, options?: RawAxiosRequestConfig): AxiosPromise<VehiclesVehicleResponse> {
            return localVarFp.vehiclesPost(body, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * VehiclesApi - object-oriented interface
 */
export class VehiclesApi extends BaseAPI {
    /**
     * 
     * @summary List vehicles
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public vehiclesGet(options?: RawAxiosRequestConfig) {
        return VehiclesApiFp(this.configuration).vehiclesGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Delete a vehicle
     * @param {number} id Vehicle ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public vehiclesIdDelete(id: number, options?: RawAxiosRequestConfig) {
        return VehiclesApiFp(this.configuration).vehiclesIdDelete(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get a vehicle
     * @param {number} id Vehicle ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public vehiclesIdGet(id: number, options?: RawAxiosRequestConfig) {
        return VehiclesApiFp(this.configuration).vehiclesIdGet(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary CreateVehicle ...
     * @param {VehiclesCreateVehicleRequest} body Vehicle payload
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public vehiclesPost(body: VehiclesCreateVehicleRequest, options?: RawAxiosRequestConfig) {
        return VehiclesApiFp(this.configuration).vehiclesPost(body, options).then((request) => request(this.axios, this.basePath));
    }
}



