CREATE TABLE IF NOT EXISTS gpspoints (
	id SERIAL PRIMARY KEY,
	vehicle_id INTEGER NOT NULL REFERENCES vehicles(id) ON DELETE CASCADE,
	bearing FLOAT NOT NULL DEFAULT 0,
	latitude FLOAT NOT NULL,
	longitude FLOAT NOT NULL,
	timestamp BIGINT NOT NULL DEFAULT 0,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)
