// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/gps": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "gps"
                ],
                "summary": "List GPS devices",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/gps.GpsResponse"
                            }
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "gps"
                ],
                "summary": "Register a GPS device",
                "parameters": [
                    {
                        "description": "GPS payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/gps.CreateGpsRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/gps.GpsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/gps-points": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "gps-points"
                ],
                "summary": "List GPS points",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/gpspoints.GpsPointResponse"
                            }
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "gps-points"
                ],
                "summary": "Record a GPS point",
                "parameters": [
                    {
                        "description": "GPS point payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/gpspoints.CreateGpsPoint"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/gpspoints.GpsPointResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/gps/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "gps"
                ],
                "summary": "Get a GPS device",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "GPS ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/gps.GpsResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "tags": [
                    "gps"
                ],
                "summary": "Delete a GPS device",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "GPS ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/gps/{id}/history": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "gps"
                ],
                "summary": "Get a GpsHistory ...",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "GPS ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/gps.GpsHistoryResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/vehicles": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "vehicles"
                ],
                "summary": "List vehicles",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/vehicles.VehicleResponse"
                            }
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "vehicles"
                ],
                "summary": "CreateVehicle ...",
                "parameters": [
                    {
                        "description": "Vehicle payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/vehicles.CreateVehicleRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/vehicles.VehicleResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/vehicles/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "vehicles"
                ],
                "summary": "Get a vehicle",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Vehicle ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/vehicles.VehicleResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "tags": [
                    "vehicles"
                ],
                "summary": "Delete a vehicle",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Vehicle ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "gps.Coordinate": {
            "type": "object",
            "required": [
                "latitude",
                "longitude",
                "updated_at"
            ],
            "properties": {
                "latitude": {
                    "type": "number"
                },
                "longitude": {
                    "type": "number"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "gps.CreateGpsRequest": {
            "type": "object",
            "required": [
                "sn",
                "vehicle_id"
            ],
            "properties": {
                "sn": {
                    "type": "string"
                },
                "vehicle_id": {
                    "type": "integer"
                }
            }
        },
        "gps.GpsHistoryResponse": {
            "type": "object",
            "required": [
                "coordinates",
                "gps_id",
                "gps_sn"
            ],
            "properties": {
                "coordinates": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/gps.Coordinate"
                    }
                },
                "gps_id": {
                    "type": "integer"
                },
                "gps_sn": {
                    "type": "string"
                }
            }
        },
        "gps.GpsResponse": {
            "type": "object",
            "required": [
                "created_at",
                "id",
                "last_coordinate",
                "sn",
                "vehicle"
            ],
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "last_coordinate": {
                    "$ref": "#/definitions/gps.Coordinate"
                },
                "sn": {
                    "type": "string"
                },
                "vehicle": {
                    "$ref": "#/definitions/vehicles.VehicleResponse"
                }
            }
        },
        "gpspoints.CreateGpsPoint": {
            "type": "object",
            "required": [
                "bearing",
                "gps_id",
                "latitude",
                "longitude",
                "timestamp"
            ],
            "properties": {
                "bearing": {
                    "type": "number"
                },
                "gps_id": {
                    "type": "integer"
                },
                "latitude": {
                    "type": "number"
                },
                "longitude": {
                    "type": "number"
                },
                "timestamp": {
                    "type": "integer"
                }
            }
        },
        "gpspoints.GpsPointResponse": {
            "type": "object",
            "required": [
                "bearing",
                "created_at",
                "gps_id",
                "id",
                "latitude",
                "longitude",
                "timestamp"
            ],
            "properties": {
                "bearing": {
                    "type": "number"
                },
                "created_at": {
                    "type": "string"
                },
                "gps_id": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "latitude": {
                    "type": "number"
                },
                "longitude": {
                    "type": "number"
                },
                "timestamp": {
                    "type": "integer"
                }
            }
        },
        "vehicles.CreateVehicleRequest": {
            "type": "object",
            "required": [
                "plate_number",
                "vehicle_type"
            ],
            "properties": {
                "plate_number": {
                    "type": "string"
                },
                "vehicle_type": {
                    "$ref": "#/definitions/vehicles.VehicleType"
                }
            }
        },
        "vehicles.VehicleResponse": {
            "type": "object",
            "required": [
                "created_at",
                "id",
                "plate_number",
                "vehicle_type"
            ],
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "plate_number": {
                    "type": "string"
                },
                "vehicle_type": {
                    "$ref": "#/definitions/vehicles.VehicleType"
                }
            }
        },
        "vehicles.VehicleType": {
            "type": "string",
            "enum": [
                "car",
                "bus",
                "truck",
                "van"
            ],
            "x-enum-varnames": [
                "Car",
                "Bus",
                "Truck",
                "Van"
            ]
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Beacon API",
	Description:      "Real-time vehicle tracking API",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
