CREATE TABLE IF NOT EXISTS gpspoints (
	id SERIAL PRIMARY KEY,
	bearing FLOAT NOT NULL DEFAULT 0,
	latitude FLOAT NOT NULL,
	longitude FLOAT NOT NULL,
	gps_id INTEGER NOT NULL REFERENCES gps_devices(id),
	timestamp BIGINT NOT NULL DEFAULT 0,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)
