CREATE TABLE IF NOT EXISTS gpspoints (
	id SERIAL PRIMARY KEY,
	latitude FLOAT NOT NULL,
	longitude FLOAT NOT NULL,
	gps_id INTEGER NOT NULL REFERENCES gps(id),
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)
