CREATE TABLE IF NOT EXISTS locations (
	id SERIAL PRIMARY KEY,
	latitude FLOAT NOT NULL,
	longitude FLOAT NOT NULL,
	assignment_id INTEGER NOT NULL REFERENCES assignments(id),
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)
