CREATE TABLE IF NOT EXISTS assignments (
	id SERIAL PRIMARY KEY,
	vehicle_id INTEGER NOT NULL UNIQUE REFERENCES vehicles(id),
	rider_id INTEGER NOT NULL UNIQUE REFERENCES riders(id),
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)
